# Generated by Django 5.2 on 2025-05-05 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_skill",
                    models.CharField(max_length=50, verbose_name="Skill name"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("full_name", models.CharField(max_length=50, verbose_name="Имя")),
                ("role", models.CharField(max_length=60, verbose_name="роль")),
                (
                    "photo_url",
                    models.ImageField(upload_to="images/", verbose_name="фото"),
                ),
                ("resume_url", models.URLField(verbose_name="резюме линк")),
                ("profile_url", models.URLField(verbose_name="профиль линк")),
                (
                    "skills",
                    models.ManyToManyField(to="student.skill", verbose_name="навыки"),
                ),
            ],
            options={
                "verbose_name": "студент",
                "verbose_name_plural": "Студенты",
            },
        ),
        migrations.CreateModel(
            name="StudentProfiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Общее описание"),
                ),
                ("about", models.TextField(blank=True, verbose_name='"Обо мне"')),
                (
                    "resume_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка на PDF"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "telegram",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Telegram"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=30, verbose_name="Телефон"),
                ),
                (
                    "relocation_ready",
                    models.BooleanField(default=False, verbose_name="Готов к переезду"),
                ),
                (
                    "relocation_city",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Город для переезда"
                    ),
                ),
                (
                    "experience",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Опыт работы"
                    ),
                ),
                (
                    "education",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Образование"
                    ),
                ),
                (
                    "projects",
                    models.JSONField(blank=True, default=list, verbose_name="Проекты"),
                ),
                (
                    "socials",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Ссылки на соцсети и платформы",
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        blank=True,
                        to="student.skill",
                        verbose_name="Технические навыки и стек",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.student",
                        verbose_name="Ссылка на студента",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль студента",
                "verbose_name_plural": "Профили студентов",
                "ordering": ["student__full_name"],
            },
        ),
    ]
