# Generated by Django 5.2 on 2025-05-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="photo_url",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/", verbose_name="фото"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="resume_url",
            field=models.URLField(blank=True, null=True, verbose_name="резюме линк"),
        ),
    ]
