# Generated by Django 5.2 on 2025-05-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_alter_student_photo_url_alter_student_resume_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofiles",
            name="education",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="Образование"
            ),
        ),
        migrations.AlterField(
            model_name="studentprofiles",
            name="experience",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="Опыт работы"
            ),
        ),
        migrations.AlterField(
            model_name="studentprofiles",
            name="projects",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="Проекты"
            ),
        ),
        migrations.AlterField(
            model_name="studentprofiles",
            name="socials",
            field=models.JSONField(
                blank=True,
                default=dict,
                null=True,
                verbose_name="Ссылки на соцсети и платформы",
            ),
        ),
    ]
