# Generated by Django 5.2 on 2025-09-11 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="telegram_chat_id",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="TG chat id"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="telegram_user_id",
            field=models.BigIntegerField(
                blank=True, db_index=True, null=True, verbose_name="TG user id"
            ),
        ),
        migrations.CreateModel(
            name="InternshipApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employer_name",
                    models.CharField(max_length=255, verbose_name="Работодатель"),
                ),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "В ожидании"),
                            ("accepted", "Принята"),
                            ("rejected", "Отклонена"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "student_response",
                    models.CharField(
                        choices=[
                            ("accepted", "Принято"),
                            ("rejected", "Отклонено"),
                            ("pending", "Ожидает"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Ответ студента",
                    ),
                ),
                (
                    "moderator_response",
                    models.CharField(
                        choices=[
                            ("accepted", "Принято"),
                            ("rejected", "Отклонено"),
                            ("pending", "Ожидает"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Ответ куратора",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="student.student",
                        verbose_name="Студент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на стажировку",
                "verbose_name_plural": "Заявки на стажировку",
            },
        ),
    ]
