# Generated by Django 5.2 on 2025-05-05 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0003_alter_studentprofiles_education_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skill",
            options={"verbose_name": "скилл", "verbose_name_plural": "скиллы"},
        ),
        migrations.RenameField(
            model_name="student",
            old_name="skills",
            new_name="top_skills",
        ),
        migrations.RemoveField(
            model_name="student",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="student",
            name="resume_url",
        ),
        migrations.AddField(
            model_name="student",
            name="short_description",
            field=models.TextField(blank=True, verbose_name=""),
        ),
        migrations.CreateModel(
            name="StudentDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Общее описание"),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        blank=True,
                        to="student.skill",
                        verbose_name="Технические навыки и стек",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.student",
                        verbose_name="Ссылка на студента",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль студента",
                "verbose_name_plural": "Профили студентов",
                "ordering": ["student__full_name"],
            },
        ),
        migrations.DeleteModel(
            name="StudentProfiles",
        ),
    ]
