# Generated by Django 5.2 on 2025-09-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0003_student_telegram_chat_id_student_telegram_user_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialty",
            name="skills",
            field=models.ManyToManyField(
                blank=True,
                related_name="specialties",
                to="student.skill",
                verbose_name="Навыки специальности",
            ),
        ),
    ]
