# Generated by Django 5.2 on 2025-05-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "student",
            "0004_alter_skill_options_rename_skills_student_top_skills_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="top_skills",
            field=models.ManyToManyField(
                null=True, to="student.skill", verbose_name="навыки"
            ),
        ),
    ]
