# Generated by Django 5.2 on 2025-05-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0005_alter_student_top_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="top_skills",
            field=models.ManyToManyField(to="student.skill", verbose_name="навыки"),
        ),
    ]
