# Generated by Django 5.2 on 2025-09-11 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_user_id",
                    models.BigIntegerField(
                        unique=True, verbose_name="Telegram user id"
                    ),
                ),
                ("chat_id", models.BigIntegerField(verbose_name="Chat id")),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="TG username"
                    ),
                ),
                (
                    "is_moderator",
                    models.BooleanField(default=False, verbose_name="Куратор"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram профиль",
                "verbose_name_plural": "Telegram профили",
            },
        ),
    ]
